default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:778574218667:android:38c369c18a76ed70cfbeee",
        firebase_cli_token: "1//03Dcd7FRQ4072CgYIARAAGAMSNwF-L9IrYk2bu72HZ3BYlsMIJZatDku90sgaGy1nLiw9X51yX2CK8TBoGxX4-ADiRDFUXNa3bME",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "emantarekshabana@gmail.com",
        release_notes: "Testing something with GitHub Actions, trying to push directly from master branch",
  )
  end
end